name: flutter_wallpaper_example
description: Demonstrates how to use the flutter_wallpaper plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_wallpaper:
    path: ../




flutter:
  uses-material-design: true

