name: flutter_wallpaper
description: A Flutter plugin for managing device wallpapers on Android and iOS.
version: 0.0.1
homepage: https://github.com/akb0n/flutter_wallpaper

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  image_gallery_saver: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.akbon.flutter_wallpaper
        pluginClass: FlutterWallpaperPlugin
