name: flutter_wallpaper
description: A Flutter plugin for managing device wallpapers on Android and iOS.
version: 0.0.8
homepage: https://github.com/akb0n/flutter_wallpaper

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.29.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_image_gallery_saver: ^0.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.akbon.flutter_wallpaper
        pluginClass: FlutterWallpaperPlugin



